spring.application.name=warehouseManagement

#  URL
spring.datasource.url=jdbc:mysql://localhost:3306/warehouse_management?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
# USerName Password
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# MyBatis config
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.mvc.static-path-pattern=/static/**

# JWT配置
warehouse.app.jwtSecret=warehouseManagementSecurityJWTSecretKey123456789
warehouse.app.jwtExpirationMs=86400000